name: Java Ci

on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          distribution: 'adopt'
          java-version: '20'

      - name: Run test
        run: mvn clean test
